[build]
  base = "preview"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Production context
[context.production]
  command = "npm install && npm run build"

# Deploy Preview context
[context.deploy-preview]
  command = "npm install && npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
