[build]
  command = """
    mkdir -p docs-site &&
    cd docs-site &&
    npm init -y &&
    npm install @docusaurus/core @docusaurus/preset-classic react react-dom clsx &&
    npm install -D @babel/core @babel/preset-env &&
    npm run build || (ls -la && pwd && cat npm-debug.log)
  """
  publish = "docs-site/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Production context
[context.production]
  command = "cd docs-site && npm install && npm run build"

# Deploy Preview context
[context.deploy-preview]
  command = "cd docs-site && npm install && npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
