[build]
  publish = "docs-site/build"
  command = "cd docs-site && npm install && npm install @docusaurus/core @docusaurus/preset-classic react react-dom clsx @babel/core @babel/preset-env && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
