[build]
  base = "preview/"
  publish = "preview/"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Production context
[context.production]
  command = "npm install && npm run build"

# Deploy Preview context
[context.deploy-preview]
  command = "npm install && npm run build"

# Branch Deploy context
[context.branch-deploy]
  command = "npm install && npm run build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "lighthouse-results"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:;"
