[build]
  command = """
    mkdir -p preview &&
    cd preview &&
    npm init -y &&
    npm install @docusaurus/core @docusaurus/preset-classic react react-dom &&
    npm run build
  """
  publish = "preview/build"

[build.environment]
  NODE_VERSION = "18"

# Production context
[context.production]
  command = "cd preview && npm install && npm run build"

# Deploy Preview context
[context.deploy-preview]
  command = "cd preview && npm install && npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
