[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/docs/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/docs/*"
  to = "/docs/:splat"
  status = 301
  force = true
