[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs"
  to = "/"
  status = 301
  force = true
